/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;
import java.net.MalformedURLException;


public class App {
    public void getGreeting() throws InterruptedException, MalformedURLException {
        TestCases test = new TestCases(); // Initialize your test class

        //TODO: call your test case functions one after other here

        try {
            test.testCase01();
            test.testCase02();
        } catch (InterruptedException e) {
            e.printStackTrace();
        } finally {
            test.endTest(); // Ensure that the browser is closed after all tests
        }

    
    }

    public static void main(String[] args) throws InterruptedException, MalformedURLException {
        new App().getGreeting();
    }
}
